version: "3.8"
services: 
  konoha:
    build: ./src
    tty: true
    working_dir: /workspace/konoha/app
    entrypoint: bash ./entrypoint.sh --dev
    links: 
      - mysql
    volumes:
      - ./src:/workspace/konoha
  mysql:
    image: mysql:8.0
    restart: always
    env_file: 
      - ./.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./src/db/data:/var/lib/mysql
      - ./src/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./src/db/sql:/docker-entrypoint-initdb.d
    ports: 
      - 13306:3306