version: "3.8"
services: 
  konoha:
    build: ./src
    tty: true
    working_dir: /workspace/konoha/app
    entrypoint: bash ./entrypoint.sh --dev
    links: 
      - mysql
    volumes:
      - ./src:/workspace/konoha
  api:
    build: ./src
    tty: true
    working_dir: /workspace/konoha/app
    entrypoint: bash ./entrypoint.api.sh --dev
    links: 
      - mysql
    volumes:
      - ./src:/workspace/konoha
    ports:
      - 8765:8765
  nuxt:
    build: ./web/frontend
    tty: true
    command: yarn dev
    env_file:
      - ./.env
    environment: 
      HOST: "0.0.0.0"
      PORT: "3000"
    volumes:
      - ./web/frontend:/app
    ports:
      - 3000:3000
  mysql:
    image: mysql:8.0
    restart: always
    env_file: 
      - ./.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./src/db/data:/var/lib/mysql
      - ./src/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./src/db/sql:/docker-entrypoint-initdb.d
    ports: 
      - 13306:3306