version: "3.8"
services: 
  konoha:
    build: ./src
    tty: true
    working_dir: /workspace/konoha/app
    entrypoint: bash ./entrypoint.sh --prod
    links: 
      - mysql
    volumes:
      - ./src:/workspace/konoha
  api:
    build: ./src
    tty: true
    working_dir: /workspace/konoha/app
    entrypoint: bash ./entrypoint.api.sh
    links: 
      - mysql
    volumes:
      - ./src:/workspace/konoha
    ports:
      - 9876:8765
  nuxt:
    build:
      dockerfile: Prod.Dockerfile
      context: ./web/frontend
    tty: true
    entrypoint: yarn start
    env_file:
      - ./.env
    environment: 
      HOST: "0.0.0.0"
      PORT: "6060"
    volumes:
      - ./web/frontend:/app
      - /app/node_modules
      - /app/.nuxt
    ports:
      - 6060:6060
  mysql:
    image: mysql:8.0
    restart: always
    env_file: 
      - ./.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/mysql
      - /etc/mysql/conf.d/my.cnf
      - /docker-entrypoint-initdb.d
    ports: 
      - 13306:3306