""""2020_08_02_13_14_55"

Revision ID: 0b3cc793b626
Revises: 104a7086e37c
Create Date: 2020-08-02 13:14:55.341877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3cc793b626'
down_revision = '104a7086e37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
