""""2020_08_12_09_03_25"

Revision ID: 0dc90864d6bf
Revises: 979c3c02c5fc
Create Date: 2020-08-12 09:03:26.089591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc90864d6bf'
down_revision = '979c3c02c5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
