""""2020_08_02_12_58_14"

Revision ID: 104a7086e37c
Revises: acecf3fad78d
Create Date: 2020-08-02 12:58:14.412002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104a7086e37c'
down_revision = 'acecf3fad78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
