""""2020_08_03_18_03_14"

Revision ID: 118df4f32ab0
Revises: 499153f6be3b
Create Date: 2020-08-03 18:03:14.521587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118df4f32ab0'
down_revision = '499153f6be3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
