""""2020_08_01_13_10_05"

Revision ID: 27574b9b0e5b
Revises: b595e30c39fa
Create Date: 2020-08-01 13:10:06.271377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27574b9b0e5b'
down_revision = 'b595e30c39fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
