""""2020_08_01_12_55_32"

Revision ID: 2cc7df162899
Revises: db884da49e63
Create Date: 2020-08-01 12:55:32.407497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc7df162899'
down_revision = 'db884da49e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
