"""2020_08_01_14_44_02

Revision ID: 357cde61cdc7
Revises: 3781d71ca495
Create Date: 2020-08-01 14:44:03.058989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357cde61cdc7'
down_revision = '3781d71ca495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
