""""2020_08_01_14_43_41"

Revision ID: 3781d71ca495
Revises: 83f6fbff0c68
Create Date: 2020-08-01 14:43:41.562211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3781d71ca495'
down_revision = '83f6fbff0c68'
branch_labels = None
depends_on = None

  
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
