""""2020_08_03_15_37_14"

Revision ID: 499153f6be3b
Revises: 5b201de6f6bc
Create Date: 2020-08-03 15:37:15.221499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499153f6be3b'
down_revision = '5b201de6f6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
