""""2020_08_10_22_37_20"

Revision ID: 4d2148683ca9
Revises: d739e1a461d1
Create Date: 2020-08-10 22:37:21.420164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2148683ca9'
down_revision = 'd739e1a461d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
