""""2020_08_01_14_41_42"

Revision ID: 4d3b6e148268
Revises: 6622bbc73ba5
Create Date: 2020-08-01 14:41:43.100661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3b6e148268'
down_revision = '6622bbc73ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
