""""2020_08_03_18_04_46"

Revision ID: 501a0f3fcffb
Revises: 118df4f32ab0
Create Date: 2020-08-03 18:04:46.333014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501a0f3fcffb'
down_revision = '118df4f32ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
