""""2020_08_12_16_58_14"

Revision ID: 55a85aac5df4
Revises: 0dc90864d6bf
Create Date: 2020-08-12 16:58:15.229333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a85aac5df4'
down_revision = '0dc90864d6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
