""""2020_08_01_12_57_49"

Revision ID: 568686112741
Revises: 2cc7df162899
Create Date: 2020-08-01 12:57:49.357191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568686112741'
down_revision = '2cc7df162899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
