""""2020_08_02_05_58_50"

Revision ID: 5794be01e6ce
Revises: a1ded004f755
Create Date: 2020-08-02 05:58:50.730902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5794be01e6ce'
down_revision = 'a1ded004f755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
