""""2020_08_03_15_33_46"

Revision ID: 5b201de6f6bc
Revises: e003b3d6feee
Create Date: 2020-08-03 15:33:47.290469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b201de6f6bc'
down_revision = 'e003b3d6feee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
