"""2020_08_01_14_39_07

Revision ID: 6622bbc73ba5
Revises: c34d2be54433
Create Date: 2020-08-01 14:39:07.732868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6622bbc73ba5'
down_revision = 'c34d2be54433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
