""""2020_08_25_14_38_12"

Revision ID: 6d210a45ff9f
Revises: 81285afcf52c
Create Date: 2020-08-25 14:38:12.425381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d210a45ff9f'
down_revision = '81285afcf52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
