""""2020_08_25_14_35_59"

Revision ID: 81285afcf52c
Revises: ccb110db4d43
Create Date: 2020-08-25 14:35:59.383575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81285afcf52c'
down_revision = 'ccb110db4d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
