""""2020_08_01_14_43_11"

Revision ID: 83f6fbff0c68
Revises: c24c39cb2a78
Create Date: 2020-08-01 14:43:11.594865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f6fbff0c68'
down_revision = 'c24c39cb2a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
