""""2020_08_12_19_22_26"

Revision ID: 943317a7e266
Revises: ff4d8dabd29b
Create Date: 2020-08-12 19:22:26.954007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943317a7e266'
down_revision = 'ff4d8dabd29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
