""""2020_08_11_17_15_12"

Revision ID: 979c3c02c5fc
Revises: 4d2148683ca9
Create Date: 2020-08-11 17:15:12.711213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979c3c02c5fc'
down_revision = '4d2148683ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
