""""2020_08_25_14_31_27"

Revision ID: 9f37517a21f4
Revises: f7321b20d2f4
Create Date: 2020-08-25 14:31:28.094070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f37517a21f4'
down_revision = 'f7321b20d2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
