""""2020_08_02_04_42_17"

Revision ID: a1ded004f755
Revises: 6a8248c87795
Create Date: 2020-08-02 04:42:17.381150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ded004f755'
down_revision = '6a8248c87795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
