""""2020_08_01_11_58_50"

Revision ID: a41fe5747c53
Revises: 
Create Date: 2020-08-01 11:58:50.564523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41fe5747c53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=255), server_default='!>', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hook',
    sa.Column('guild', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('hookurl', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('hookurl')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hook')
    op.drop_table('guild')
    # ### end Alembic commands ###
