""""2020_08_02_12_55_04"

Revision ID: acecf3fad78d
Revises: 5794be01e6ce
Create Date: 2020-08-02 12:55:04.794851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acecf3fad78d'
down_revision = '5794be01e6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
