""""2020_08_01_13_03_30"

Revision ID: b595e30c39fa
Revises: b85f0e44d69e
Create Date: 2020-08-01 13:03:30.343083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b595e30c39fa'
down_revision = 'b85f0e44d69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
