""""2020_08_01_13_00_38"

Revision ID: b85f0e44d69e
Revises: 568686112741
Create Date: 2020-08-01 13:00:39.230939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85f0e44d69e'
down_revision = '568686112741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
