"""2020_08_01_14_42_01

Revision ID: c24c39cb2a78
Revises: 4d3b6e148268
Create Date: 2020-08-01 14:42:01.361840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24c39cb2a78'
down_revision = '4d3b6e148268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
