""""2020_08_01_13_10_21"

Revision ID: c34d2be54433
Revises: 27574b9b0e5b
Create Date: 2020-08-01 13:10:22.092353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34d2be54433'
down_revision = '27574b9b0e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
