""""2020_08_25_14_35_17"

Revision ID: ccb110db4d43
Revises: 9f37517a21f4
Create Date: 2020-08-25 14:35:17.572384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb110db4d43'
down_revision = '9f37517a21f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
