"""2020_08_01_14_45_19

Revision ID: ccd6df853397
Revises: 357cde61cdc7
Create Date: 2020-08-01 14:45:19.624333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd6df853397'
down_revision = '357cde61cdc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
