""""2020_08_04_12_09_17"

Revision ID: d11dd7d0c68d
Revises: 501a0f3fcffb
Create Date: 2020-08-04 12:09:18.222873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11dd7d0c68d'
down_revision = '501a0f3fcffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
