""""2020_08_09_17_37_46"

Revision ID: d739e1a461d1
Revises: d11dd7d0c68d
Create Date: 2020-08-09 17:37:46.605206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd739e1a461d1'
down_revision = 'd11dd7d0c68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
