""""2020_08_01_12_11_36"

Revision ID: db884da49e63
Revises: a41fe5747c53
Create Date: 2020-08-01 12:11:37.117471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db884da49e63'
down_revision = 'a41fe5747c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
