""""2020_08_03_15_00_06"

Revision ID: e003b3d6feee
Revises: 0b3cc793b626
Create Date: 2020-08-03 15:00:06.536755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e003b3d6feee'
down_revision = '0b3cc793b626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
