""""2020_08_12_17_01_33"

Revision ID: ff4d8dabd29b
Revises: 55a85aac5df4
Create Date: 2020-08-12 17:01:34.115286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4d8dabd29b'
down_revision = '55a85aac5df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
